attack_trigger_img_path: "./triggers/hello_kitty.png"   # 触发图案路径
attack_train_blended_alpha: 0.2                         # 训练混合比例
attack_test_blended_alpha: 0.2                          # 测试混合比例（可与训练不同）